[package]
name = "csp2p-rs"
version = "0.1.0"
authors = ["aav@credits.com <aav@credits.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.23.0"